- name: Install required packages
  apt:
    pkg:
      - apt-transport-https
      - software-properties-common
      - wget

- name: Get GPG key
  get_url:
    url: "https://apt.grafana.com/gpg.key"
    dest: /usr/share/keyrings/grafana.key

- name: Add repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main"
    state: present

- name: Install grafana
  apt:
    name: grafana={{ version }}
    state: present
    update_cache: yes

- name: "Grafana configuration file copy"
  template:
    src: "grafana.conf.j2"
    dest: /etc/grafana/grafana.ini
  notify: event_restart_grafana

- name: "Check if Grafana is accessible."
  uri:
    url: http://localhost:3000
    method: GET
    status_code: 200
