- name: Install required packages
  apt:
    pkg:
      - apt-transport-https
      - software-properties-common
      - wget
    state: present

- name: Get GPG key
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    state: present

- name: Add repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present

- name: Update apt
  apt:
    update_cache: yes

- name: Install grafana
  apt:
    name: grafana={{ version }}
    state: present

- name: "Grafana configuration file copy"
  template:
    src: "grafana.conf.j2"
    dest: /etc/grafana/grafana.ini
  notify: event_restart_grafana

- name: "Check if Grafana is accessible."
  uri:
    url: http://localhost:3000
    method: GET
    status_code: 200
