---
- hosts: prometheus
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo
  vars:
    ansible_ssh_private_key_file: ../key/tfkey.pem
  roles:
    - prometheus

- hosts: grafana
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo
  vars:
    ansible_ssh_private_key_file: ../key/tfkey.pem
  roles:
    - grafana
