name: "Terraform"

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch: # Allows manual triggering of terraform apply

permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: terraform

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Save Inventory File
        uses: actions/upload-artifact@v3
        with:
          name: inventory-file
          path: ansible/inventory.ini

      - name: DEBUG
        run: cat ../ansible/inventory.ini

      - name: DEBUG
        run: ls -la ansible

  ansible:
    name: "Ansible"
    runs-on: ubuntu-latest
    environment: production
    needs: terraform
    defaults:
      run:
        shell: bash
        working-directory: ansible

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: DEBUG
        run: ls -la

      - name: DEBUG
        run: cat inventory.ini

      - name: Download Inventory File
        uses: actions/download-artifact@v3
        with:
          name: inventory-file

      - name: Run Ansible Playbook
        run: |
          ansible-playbook main.yml
