name: "Terraform"

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch: # Allows manual triggering of terraform apply

permissions:
  contents: read

jobs:
  terraform-init:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init
        working-directory: ../terraform

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ../terraform

  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    needs: terraform-init
    environment: production
    defaults:
      run:
        shell: bash

    steps:
      - name: Terraform Plan
        run: terraform plan
        working-directory: ../terraform

  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment: production
    defaults:
      run:
        shell: bash

    steps:
      - name: Terraform Apply
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: terraform apply -auto-approve
        working-directory: ../terraform
